import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "./_components/ui/sonner";
import { ReactQueryProvider } from "./_providers/react-query";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700", "800", "600", "500", "300"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Beware",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <ReactQueryProvider>
          {children}
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
